[package]
name = "wodencja"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8"
rustls-pemfile = "2.2"
tokio = { version = "1.44.2", features = ["macros", "rt-multi-thread"] }
tokio-rustls = "0.26"
